platform:
  - x86

environment:
  global:
    FORK_USER: ocaml
    FORK_BRANCH: master
    CYG_ROOT: C:\cygwin64
    GAMMU_PATH: "C:\\Gammu"
    GAMMU_URL: https://dl.cihar.com/gammu/releases/windows/Gammu-1.39.0-Windows.exe
  matrix:
    - OPAM_SWITCH: 4.04.0+msvc64c
#    - OPAM_SWITCH: 4.04.0+mingw64c

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))
  # Install Gammu.
  # See https://github.com/gammu/python-gammu/blob/master/appveyor.yml
  - appveyor DownloadFile %GAMMU_URL% -FileName gammu-setup.exe
  - gammu-setup.exe /S /D=%GAMMU_PATH%

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
